# Flow-to-FIM Configuration

# AWS S3 configuration
s3:
  bucket: fimc-data
  paths:
    ripple_collections: ripple/fim_100_domain/collections/
    success_markers: benchmark/ripple_fim_100/status/success/
    error_retry: benchmark/ripple_fim_100/status/errors/retry/
    error_nonretry: benchmark/ripple_fim_100/status/errors/nonretry/
    output_base: benchmark/ripple_fim_100/

# Flow files to process
flow_files:
  - name: flows_2year.csv
    return_period: 2
  - name: flows_5year.csv
    return_period: 5
  - name: flows_10year.csv
    return_period: 10
  - name: flows_25year.csv
    return_period: 25
  - name: flows_50year.csv
    return_period: 50
  - name: flows_100year.csv
    return_period: 100

# Nomad configuration
nomad:
  # AWS nomad
  # address: http://nomad-server-test.test.nextgenwaterprediction.com:4646
  # local nomad
  address: http://127.0.0.1:4646
  job_template: f2f-runner
